TOP=..
.include "$(TOP)/mk/base.mk"

TESTTYPE=synth
TESTS=t00 t01 t02 t03 t04 t05 t06 t07 t08 t09 t10 t11

CASPFILE=simple.casp
CASPFILE.t01=t01.casp
CASPFILE.t02=t02.casp
CASPFILE.t03=t02.casp
CASPFILE.t04=t04.casp
CASPFILE.t05=t04.casp
CASPFILE.t06=t06.casp
CASPFILE.t07=t06.casp
CASPFILE.t08=t08.casp
CASPFILE.t09=t09.casp
CASPFILE.t10=../kips.casp
CASPFILE.t11=../kips.casp

.include "$(TOP)/mk/testdir.mk"
