TOP=..
.include "$(TOP)/mk/base.mk"

CASPFLAGS="-dump-solver"

SUBDIRS=\
	initial_stack \
	get_disp \
	disp_disabled \
	check_low \
	set_area \
	check_high

.include "common.mk"
.include "$(TOP)/mk/subdir.mk"

