TOP=..
.include "$(TOP)/mk/base.mk"

SUBDIRS=\
	crt0_initregs \
	crt0_savevals \
	syscalls_loadnum \
	switch_enter \
	switch_save \
	switch_load \
	switch_leave \
	cpu_irqoff \
#	setjmp-full \
	switch_all \
	longjmp-full \
	longjmp-ret \
	setjmp-ret \
# 	cacheflush \
# 	mmu_setasid \
# 	mmu_setptbase

.include "common.mk"
.include "$(TOP)/mk/subdir.mk"

