TOP=..
.include "$(TOP)/mk/base.mk"

TESTTYPE=symexec
TESTS=t00a t00b t01a t01b t02a t02b t03a t03b t04 t05

CASPFILE.t00a=test.casp
CASPFILE.t00b=test.casp
CASPFILE.t01a=test.casp
CASPFILE.t01b=test.casp
CASPFILE.t02a=test.casp
CASPFILE.t02b=test.casp
CASPFILE.t03a=test.casp
CASPFILE.t03b=test.casp
CASPFILE.t04=test.casp
CASPFILE.t05=test.casp

.include "$(TOP)/mk/testdir.mk"
