TOP=..
.include "$(TOP)/mk/base.mk"

TESTTYPE=interp
TESTS=\
	t00 t01 t02 t03 t04 t05 t06 t07 t08 t09 \
	t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 \
	t20 t21 t22 t23 t24 t25 t26 t27 t28 t29 \
	t30 t31 t32 t33

CASPFILE.t00=test.casp
CASPFILE.t01=test.casp
CASPFILE.t02=test.casp
CASPFILE.t03=test.casp
CASPFILE.t04=test.casp
CASPFILE.t05=test.casp
CASPFILE.t06=test.casp
CASPFILE.t07=test.casp
CASPFILE.t08=test.casp
CASPFILE.t09=test.casp
CASPFILE.t10=test.casp
CASPFILE.t11=test.casp
CASPFILE.t12=test.casp
CASPFILE.t13=test.casp
CASPFILE.t14=test2.casp
CASPFILE.t15=test2.casp
CASPFILE.t16=test2.casp
CASPFILE.t17=test2.casp
CASPFILE.t18=test2.casp
CASPFILE.t19=test2.casp
CASPFILE.t20=test2.casp
CASPFILE.t21=test2.casp
CASPFILE.t22=test2.casp
CASPFILE.t23=test2.casp
CASPFILE.t24=test2.casp
CASPFILE.t25=test2.casp
CASPFILE.t26=test2.casp
CASPFILE.t27=test2.casp
CASPFILE.t28=t28.casp
CASPFILE.t29=t28.casp
CASPFILE.t30=t30.casp
CASPFILE.t31=t31.casp
CASPFILE.t32=t32.casp
CASPFILE.t33=t33.casp

.include "$(TOP)/mk/testdir.mk"
